# Generated by Django 5.1.1 on 2024-10-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
                ('item_status', models.BooleanField()),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'listings',
            },
        ),
    ]
