# Generated by Django 5.1.1 on 2024-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='item_status',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='description',
            field=models.CharField(default='No description provided by seller', max_length=300),
        ),
    ]
