# Generated by Django 5.1.1 on 2024-10-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_listing_item_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
