# Generated by Django 5.1.1 on 2024-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listing_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='stock',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.JSONField(default='"Empty watchlist"'),
        ),
    ]
