# Generated by Django 5.1.1 on 2024-10-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_listing_stock_user_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
