# Generated by Django 5.1.1 on 2024-10-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_user_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('bid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('buyer_id', models.IntegerField()),
                ('bid_price', models.IntegerField()),
                ('status', models.CharField(default='Unsold', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
