# Generated by Django 5.1.1 on 2024-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bids_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='buyer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
