# Generated by Django 5.1.1 on 2024-10-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bids_bid_price_alter_bids_buyer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.FloatField(null=True),
        ),
    ]
