# Generated by Django 5.1.1 on 2024-10-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auction_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
